name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
        shell: bash

      - name: Build the project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
        working-directory: src

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          ctest --test-dir tests
        working-directory: src
